version: "3.1"
services:
    db:
        image: mysql:8.0
        ports: 
            - "3308:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: distributeur
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
            
            
    interface:
      build: .
      command: python manage.py runserver 0.0.0.0:8001
      volumes:
        - .:/code
      ports:
        - "8001:8001"
      depends_on:
        - db

volumes:
    persistent:
